version: '3'
services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    environment:
       ACCEPT_EULA: "Y"
       SA_PASSWORD: Pa55w0rd2019 
       MSSQ:_PID: Express
    ports:
      - "1433:1433"
  moviess:
    build: .
    ports:
      - "8080:80"
